name: toktik
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-409.0.dev <4.0.0'

dependencies:
  animate_do: ^3.0.2
  flutter:
    sdk: flutter
  intl: ^0.18.0
  provider: ^6.0.5
  video_player: ^2.6.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/videos/
